<a href="https://colab.research.google.com/github/NikitaMelnychencko/goit-ds-hw-04/blob/main/hw_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import random

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
print(a)

m = np.array([[1, 2, 3], [4, 5, 6], [4, 5, 6]], dtype=int)
print(m)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1 2 3]
 [4 5 6]
 [4 5 6]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.






In [16]:
b = np.random.randint(1, 11, size=(5, 5))
m = np.array(b, dtype=int)
print(m)

[[ 7  1  9  5  9]
 [ 7  5  9  7  6]
 [10  7  1  4  6]
 [ 8  7  1  8  6]
 [ 4  4  4  3  8]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [46]:
a = np.eye(4, k=-1, dtype=int)
print(a)

[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.


In [27]:
a = np.array(np.random.randint(11, size=5), dtype=int)
b = np.array(np.random.randint(11, size=5), dtype=int)
print(a + b)
print(a - b)
print(a * b)

[ 6 11 16  2 10]
[  6   1  -4   2 -10]
[ 0 30 60  0  0]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [28]:
a = np.array(np.random.randint(11, size=7), dtype=int)
b = np.array(np.random.randint(11, size=7), dtype=int)
print(np.dot(a, b))

212


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [39]:
m = np.array(np.random.randint(1, 11, size=(2, 2)), dtype=int)
x = np.array(np.random.randint(1, 11, size=(2, 3)), dtype=int)
print(np.dot(m, x))

[[41 36 31]
 [49 48 35]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [43]:
a = np.array(np.random.randint(1, 11, size=(3, 3)), dtype=int)
a_inv = np.linalg.inv(a)
print("a", a)
print("a_inv", a_inv)

a [[4 2 4]
 [7 6 7]
 [3 4 5]]
a_inv [[ 0.1  0.3 -0.5]
 [-0.7  0.4  0. ]
 [ 0.5 -0.5  0.5]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [54]:
a = np.eye(4, k=-1, dtype=int)
print("a", a)
b = a.T
print("b", b)

a [[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
b [[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [56]:
a = np.array(np.random.randint(1, 11, size=(3, 4)), dtype=int)
b = np.array(np.random.randint(11, size=4), dtype=int)
print(a * b)

[[ 8 80 48 15]
 [ 6 40 60 30]
 [14 40 42 15]]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [60]:
a = np.random.random((2, 3))
b = np.random.random(3)
a * b

array([[0.03750619, 0.33319878, 0.16452937],
       [0.04813597, 0.09566944, 0.28764335]])

Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [62]:
a = np.array(np.random.randint(1, 11, size=(2, 2)), dtype=int)
b = np.array(np.random.randint(1, 11, size=(2, 2)), dtype=int)
print(a*b)

[[ 4 27]
 [ 4  8]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.


In [66]:
a @ b

array([[22, 24],
       [12, 14]])

In [67]:
np.matmul(a, b)

array([[22, 24],
       [12, 14]])

Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [70]:
a = np.array(np.random.randint(1, 101, size=(5, 5)), dtype=int)
np.sum(a)

np.int64(1527)

Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [72]:
p = np.array(np.random.randint(1, 11, size=(4, 4)), dtype=int)
o = np.array(np.random.randint(1, 11, size=(4, 4)), dtype=int)
p-o

array([[-3, -2, -4,  0],
       [ 2, -6,  2,  5],
       [ 7,  5, -3, -7],
       [ 8, -4, -9,  1]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [76]:
matrix = np.random.random((3, 3))
row_sums = np.sum(matrix, axis=1).reshape(3, 1)
row_sums

array([[2.73915431],
       [2.06035487],
       [2.36073124]])

Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [85]:
p = np.array(np.random.randint(1, 101, size=(3, 4)), dtype=int)
np.square(p)

array([[3249, 2809,  729,   16],
       [ 196, 3249, 5476, 1600],
       [1600, 2916, 3249, 8464]])

Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [87]:
b = np.array(np.random.randint(51, size=4), dtype=int)
print(b)
np.square(b)

[11 49  9  8]


array([ 121, 2401,   81,   64])

Доп

Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = arr % 2 != 0
arr[mask] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [92]:
arr1D = np.array([1, 2, 3, 4, 5, 6])
arr2D = arr1D.reshape(2, 3)
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

 Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [98]:
arr2D1 = np.array(np.random.randint(1, 101, size=(3, 3)), dtype=int)
arr2D2 = np.array(np.random.randint(1, 101, size=(3, 3)), dtype=int)
np.vstack((arr2D1, arr2D2))

array([[22,  6, 52],
       [60, 39, 84],
       [ 6,  5, 49],
       [78, 63, 20],
       [56, 71, 33],
       [61, 46, 75]])

Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])

Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [111]:
a = np.array([1,2,3])
aStak =  np.concatenate((a, a, a))
aSort = np.sort(aStak.copy())
np.concatenate((aSort, aStak))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Отримайте спільні елементи між a і b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

In [113]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

 Отримайте позиції перших 5 максимальних значень у заданому масиві a

np.random.seed(100) a = np.random.uniform(1,50, 20)

In [131]:
a = np.random.uniform(1,50, 20)
sorted_indices = np.argsort(a)
sorted_indices[-5:]


array([ 9,  4,  3, 13, 10])

 Вилучіть усі значення NaN із одновимірного масиву

а=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [139]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a_clean = a[~np.isnan(a)]
a_clean

array([1., 2., 3., 5., 6., 7.])

 Обчисліть евклідову відстань між двома масивами a і b.

a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8])

In [141]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
distance = np.linalg.norm(a - b)
distance

np.float64(6.708203932499369)

 Знайдіть індекс 5-го повторення числа 1 у масиві x

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [144]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
indices[4]

np.int64(8)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

# Input np.random.seed(100) a = np.random.randint(0, 5, 10)

[0 0 3 0 2 4 2 2 2 2] #Output [False True False True False False True True True True]

In [155]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)

seen = {}
output = np.zeros(len(a), dtype=bool)

for i, val in enumerate(a):
    if val in seen:
        output[i] = True
    else:
        seen[val] = True

output

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])